### ISSUE TITLE
Do not have access to the age.csv

### ISSUE THREAD

**Issue by AliHashemi-ai** [hichamjanati/Cam-CAN-preprocessing#1]
https://github.com/hichamjanati/Cam-CAN-preprocessing/blob/7a08708de7facc1426ca2af2c844ce7a412d0886/config.py#L137

How can I access the age.csv file? What are the features of this dataframe?

**Comment by hichamjanati** [comment]
Its path is  "/storage/store/work/hjanati/datasets/data/camcan/age.csv", I cannot remember how we got it from the raw data. If you don't have access to it, tell me and I'll add it here in the repo

**Comment by AliHashemi-ai** [comment]
> Its path is "/storage/store/work/hjanati/datasets/data/camcan/age.csv",

This is a path referring to your directory right? Am I authorized to access data there? 


 I cannot remember how we got it from the raw data. If you don't have access to it, tell me and I'll add it here in the repo

**Comment by hichamjanati** [comment]
Yes you should have read access at least

**Comment by AliHashemi-ai** [comment]
Could you let me know how can I access the files in this path? You mean by using ssh?

**Comment by hichamjanati** [comment]
Ah sorry I assumed we've given you access to our servers (drago) .. i'll add it to the repo here
