### ISSUE TITLE
Name of the function

### ISSUE THREAD

**Issue by AliHashemi-ai** [hichamjanati/Cam-CAN-preprocessing#2]
https://github.com/hichamjanati/Cam-CAN-preprocessing/blob/7a08708de7facc1426ca2af2c844ce7a412d0886/compute_evoked_responses.py#L231

The name of the function here should be changed to ``get_all_subjects(kind):`` that is defined on top of this code, here. Right?  Otherwise, we are calling a function from **config.py,** i.e., ``cfg.get_subjects_list``.

**Comment by hichamjanati** [comment]
Ah sorry about the confusion, I think it's safe to remove the function `get_all_subjects` and use `cfg.get_subjects_list`. Regardless of the age filter, the latter makes sure we have all the necessary data before adding a subject to the list. (For some subjects, some files are missing)
